#ifndef _REQUESTER_STRUCTS_HTTP_STATUS_TEXT_H
#define _REQUESTER_STRUCTS_HTTP_STATUS_TEXT_H

#define _HttpStatusTextExpanded(name) name
#define HttpStatusText(code) _HttpStatusTextExpanded(HTTP_STATUS_TEXT_##code)

#define HTTP_STATUS_TEXT_0 ""

#define HTTP_STATUS_TEXT_100 "Continue"
#define HTTP_STATUS_TEXT_101 "Switching Protocols"
#define HTTP_STATUS_TEXT_102 "Processing"
#define HTTP_STATUS_TEXT_103 "Early Hints"

#define HTTP_STATUS_TEXT_200 "OK"
#define HTTP_STATUS_TEXT_201 "Created"
#define HTTP_STATUS_TEXT_202 "Accepted"
#define HTTP_STATUS_TEXT_203 "Non-Authoritative Information"
#define HTTP_STATUS_TEXT_204 "No Content"
#define HTTP_STATUS_TEXT_205 "Reset Content"
#define HTTP_STATUS_TEXT_206 "Partial Content"
#define HTTP_STATUS_TEXT_207 "Multi-Status"
#define HTTP_STATUS_TEXT_208 "Already Reported"
#define HTTP_STATUS_TEXT_226 "IM Used"

#define HTTP_STATUS_TEXT_300 "Multiple Choices"
#define HTTP_STATUS_TEXT_301 "Moved Permanently"
#define HTTP_STATUS_TEXT_302 "Found"
#define HTTP_STATUS_TEXT_303 "See Other"
#define HTTP_STATUS_TEXT_304 "Not Modified"
#define HTTP_STATUS_TEXT_305 "Use Proxy"
#define HTTP_STATUS_TEXT_307 "Temporary Redirect"
#define HTTP_STATUS_TEXT_308 "Permanent Redirect"

#define HTTP_STATUS_TEXT_400 "Bad Request"
#define HTTP_STATUS_TEXT_401 "Unauthorized"
#define HTTP_STATUS_TEXT_402 "Payment Required"
#define HTTP_STATUS_TEXT_403 "Forbidden"
#define HTTP_STATUS_TEXT_404 "Not Found"
#define HTTP_STATUS_TEXT_405 "Method Not Allowed"
#define HTTP_STATUS_TEXT_406 "Not Acceptable"
#define HTTP_STATUS_TEXT_407 "Proxy Authentication Required"
#define HTTP_STATUS_TEXT_408 "Request Timeout"
#define HTTP_STATUS_TEXT_409 "Conflict"
#define HTTP_STATUS_TEXT_410 "Gone"
#define HTTP_STATUS_TEXT_411 "Length Required"
#define HTTP_STATUS_TEXT_412 "Precondition Failed"
#define HTTP_STATUS_TEXT_413 "Payload Too Large"
#define HTTP_STATUS_TEXT_414 "URI Too Long"
#define HTTP_STATUS_TEXT_415 "Unsupported Media Type"
#define HTTP_STATUS_TEXT_416 "Range Not Satisfiable"
#define HTTP_STATUS_TEXT_417 "Expectation Failed"
#define HTTP_STATUS_TEXT_418 "I'm a teapot"
#define HTTP_STATUS_TEXT_421 "Misdirected Request"
#define HTTP_STATUS_TEXT_422 "Unprocessable Entity"
#define HTTP_STATUS_TEXT_423 "Locked"
#define HTTP_STATUS_TEXT_424 "Failed Dependency"
#define HTTP_STATUS_TEXT_425 "Too Early"
#define HTTP_STATUS_TEXT_426 "Upgrade Required"
#define HTTP_STATUS_TEXT_428 "Precondition Required"
#define HTTP_STATUS_TEXT_429 "Too Many Requests"
#define HTTP_STATUS_TEXT_431 "Request Header Fields Too Large"
#define HTTP_STATUS_TEXT_451 "Unavailable For Legal Reasons"

#define HTTP_STATUS_TEXT_500 "Internal Server Error"
#define HTTP_STATUS_TEXT_501 "Not Implemented"
#define HTTP_STATUS_TEXT_502 "Bad Gateway"
#define HTTP_STATUS_TEXT_503 "Service Unavailable"
#define HTTP_STATUS_TEXT_504 "Gateway Timeout"
#define HTTP_STATUS_TEXT_505 "HTTP Version Not Supported"
#define HTTP_STATUS_TEXT_506 "Variant Also Negotiates"
#define HTTP_STATUS_TEXT_507 "Insufficient Storage"
#define HTTP_STATUS_TEXT_508 "Loop Detected"
#define HTTP_STATUS_TEXT_510 "Not Extended"
#define HTTP_STATUS_TEXT_511 "Network Authentication Required"

#endif