#ifndef _REQUESTER_STRUCTS_MIME_TYPE_H
#define _REQUESTER_STRUCTS_MIME_TYPE_H

#include <stddef.h>

typedef enum _MIMEType MIMEType;

enum _MIMEType {
    MIME_UNKNOWN,
    MIME_APPLICATION_JSON,
    MIME_APPLICATION_XML,
    MIME_APPLICATION_X_WWW_FORM_URLENCODED,
    MIME_MULTIPART_FORM_DATA,
    MIME_TEXT_PLAIN,
    MIME_TEXT_HTML,
    MIME_TEXT_CSS,
    MIME_TEXT_JAVASCRIPT,
    MIME_IMAGE_PNG,
    MIME_IMAGE_JPEG,
    MIME_IMAGE_WEBP,
    MIME_IMAGE_GIF,
    MIME_IMAGE_BMP,
    MIME_AUDIO_MPEG,
    MIME_AUDIO_OGG,
    MIME_AUDIO_WAV,
    MIME_AUDIO_FLAC,
    MIME_VIDEO_MP4,
    MIME_VIDEO_AVI,
    MIME_VIDEO_WEBM,
    MIME_APPLICATION_PDF,
    MIME_APPLICATION_ZIP,
    MIME_APPLICATION_OCTET_STREAM,
    MIME_APPLICATION_X_TAR,
    MIME_APPLICATION_GZIP,
    MIME_FONT_WOFF,
    MIME_FONT_WOFF2,
    MIME_FONT_TTF,
    MIME_FONT_EOT,
    MIME_APPLICATION_RSS_XML,
    MIME_APPLICATION_X_RAR_COMPRESSION,
    MIME_APPLICATION_JS,
    MIME_APPLICATION_VND_MS_EXCEL,
    MIME_APPLICATION_VND_MS_POWERPOINT,
    MIME_APPLICATION_VND_MS_WORD,
    MIME_APPLICATION_JSONLD
};

MIMEType MIMEType_FromFileName(const char* file_name);

MIMEType MIMEType_FromString(const char* src, size_t src_size);

const char* MIMEType_ToString(MIMEType mt);

#endif