#ifndef _REQUESTER_STRUCTS_MIME_TYPE_TEXT_H
#define _REQUESTER_STRUCTS_MIME_TYPE_TEXT_H

#define MIME_UNKNOWN_TEXT "application/octet-stream"
#define MIME_APPLICATION_JSON_TEXT "application/json"
#define MIME_APPLICATION_XML_TEXT "application/xml"
#define MIME_APPLICATION_X_WWW_FORM_URLENCODED_TEXT "application/x-www-form-urlencoded"
#define MIME_MULTIPART_FORM_DATA_TEXT "multipart/form-data"
#define MIME_TEXT_PLAIN_TEXT "text/plain"
#define MIME_TEXT_HTML_TEXT "text/html"
#define MIME_TEXT_CSS_TEXT "text/css"
#define MIME_TEXT_JAVASCRIPT_TEXT "text/javascript"
#define MIME_IMAGE_PNG_TEXT "image/png"
#define MIME_IMAGE_JPEG_TEXT "image/jpeg"
#define MIME_IMAGE_WEBP_TEXT "image/webp"
#define MIME_IMAGE_GIF_TEXT "image/gif"
#define MIME_IMAGE_BMP_TEXT "image/bmp"
#define MIME_AUDIO_MPEG_TEXT "audio/mpeg"
#define MIME_AUDIO_OGG_TEXT "audio/ogg"
#define MIME_AUDIO_WAV_TEXT "audio/wav"
#define MIME_AUDIO_FLAC_TEXT "audio/flac"
#define MIME_VIDEO_MP4_TEXT "video/mp4"
#define MIME_VIDEO_AVI_TEXT "video/avi"
#define MIME_VIDEO_WEBM_TEXT "video/webm"
#define MIME_APPLICATION_PDF_TEXT "application/pdf"
#define MIME_APPLICATION_ZIP_TEXT "application/zip"
#define MIME_APPLICATION_OCTET_STREAM_TEXT "application/octet-stream"
#define MIME_APPLICATION_X_TAR_TEXT "application/x-tar"
#define MIME_APPLICATION_GZIP_TEXT "application/gzip"
#define MIME_FONT_WOFF_TEXT "font/woff"
#define MIME_FONT_WOFF2_TEXT "font/woff2"
#define MIME_FONT_TTF_TEXT "font/ttf"
#define MIME_FONT_EOT_TEXT "font/eot"
#define MIME_APPLICATION_RSS_XML_TEXT "application/rss+xml"
#define MIME_APPLICATION_X_RAR_COMPRESSION_TEXT "application/x-rar-compressed"
#define MIME_APPLICATION_JS_TEXT "application/javascript"
#define MIME_APPLICATION_VND_MS_EXCEL_TEXT "application/vnd.ms-excel"
#define MIME_APPLICATION_VND_MS_POWERPOINT_TEXT "application/vnd.ms-powerpoint"
#define MIME_APPLICATION_VND_MS_WORD_TEXT "application/vnd.ms-word"
#define MIME_APPLICATION_JSONLD_TEXT "application/ld+json"

#endif