#ifndef _REQUESTER_CONFIG_H
#define _REQUESTER_CONFIG_H

#define HTTP_DEFAULT_REQUEST_VERSION HTTP_VERSION_1_1
#define HTTP_DEFAULT_REQUEST_METHOD HTTP_METHOD_GET

#define CHUNK_SIZE_FILE_CONTENT_SEND 2048
#define CHUNK_SIZE_STREAM_CONTENT_SEND 1024
#define CHUNK_SIZE_STREAM_TO_FILE_READ 1024

#define HTTP_MAXLEN_URL 2048
#define HTTP_MAXLEN_HEADER_NAME 400
#define HTTP_MAXLEN_HEADER_VALUE 400

#define HTTP_RESPONSE_READ_CHUNK 2048
#define HTTP_GSTREAM_READ_CHUNK 1024

#define HTTP_MULTIPART_DEFAULT_BOUNDARY "--------------123123"

#endif