#ifndef _REQUESTER_HTTP_DEFAULT_H
#define _REQUESTER_HTTP_DEFAULT_H

#define HTTP_DELIMITER_MESSAGE_LINE "\r\n"
#define HTTP_DELIMITER_MESSAGE_PAYLOAD "\r\n\r\n"
#define HTTP_DELIMITER_MESSAGE_HEADLINE " "
#define HTTP_DELIMITER_HEADER ":"
#define HTTP_DELIMITER_URL_PROTOCOL "://"
#define HTTP_DELIMITER_URL_USERPWD ":"
#define HTTP_DELIMITER_URL_HOST "@"
#define HTTP_DELIMITER_URL_PORT ":"
#define HTTP_DELIMITER_URL_RESOURCE "/"
#define HTTP_DELIMITER_URL_QUERY "?"
#define HTTP_DELIMITER_URL_FRAGMENT "#"
#define HTTP_DELIMITER_QUERY_VALUE "="
#define HTTP_DELIMITER_QUERY_PAIR "&"

#define HTTP_PORT 80
#define HTTPS_PORT 443

#endif